### ISSUE TITLE
test.py Build failed

### ISSUE THREAD

**Issue by nimahkh** [nsnam/ns-3-dev-git#23]
hi friends , when i run test.py i got following error : 
`Build failed
 -> task failed (exit status 1): 
	{task 140363016135952: cxx uan-mac-cw.cc -> uan-mac-cw.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-fPIC', '-pthread', '-Ibuild', '-I.', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DSQLITE3=1', '-DHAVE_IF_TUN_H=1', '-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"', '-DHAVE_PYTHON_H=1', '-DENABLE_GSL', '../src/uan/model/uan-mac-cw.cc', '-c', '-o', 'src/uan/model/uan-mac-cw.cc.1.o']`

i'm using ubuntu 16.04

**Comment by tomhenderson** [comment]
If you continue to have problems, please ask your question on ns-3-users@googlegroups.com.
