### ISSUE TITLE
code problem: dsdv-rtable.cc

### ISSUE THREAD

**Issue by chen-chen-ju** [nsnam/ns-3-dev-git#45]
In function:   RoutingTable::Purge (std::map<Ipv4Address, RoutingTableEntry> & removedAddresses)

a line code:
if ((j->second.GetNextHop () == i->second.GetDestination ()) && (i->second.GetHop () != j->second.GetHop ()))

I think i->second.GetDestination () should be  i->second.GetNextHop () , because when the route is timeout, i->second.GetNextHop () can't reach

**Comment by chen-chen-ju** [comment]
The code is right, my mistake

**Comment by tomhenderson** [comment]
Hello chen-chen-ju, in the future, please post future issues to GitLab.com, not GitHub.com.
